name: gal
description: Flutter Plugin for Saving Image/Video to the Photo Gallery | How to Save Image/Video to the Photo Gallery in Flutter
version: 2.2.0
homepage: https://pub.dev/packages/gal
repository: https://github.com/natsuk4ze/gal
documentation: https://github.com/natsuk4ze/gal/wiki
funding: 
 - https://github.com/sponsors/natsuk4ze

topics:
 - gallery
 - video
 - image
 - photos
 - util

screenshots:
 - description: 'Logo of gal package.'
   path: assets/logo.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.gal
        pluginClass: GalPlugin
      ios:
        pluginClass: GalPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: GalPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: GalPluginCApi
