# Runner details on https://github.com/actions/runner-images/tree/main/images

name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}



  ios:
    needs: set-up
    timeout-minutes: 60
    strategy:
      matrix:
        ios-version: [17]
      fail-fast: false
    runs-on: macos-14
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        timeout-minutes: 10
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: List available simulators
        run: xcrun simctl list --json devices available

      - name: Boot ios simulator
        uses: futureware-tech/simulator-action@v2
        with:
          os: ios
          os_version: ^${{ matrix.ios-version }}
      
      - name: Grant permission
        run: |
          brew tap wix/brew
          brew install applesimutils
          cd example
          applesimutils --booted --bundle studio.midoridesign.galExample --setPermissions photos=YES

      - name: Run integration tests
        id: Run-integration-tests
        continue-on-error: true
        timeout-minutes: 15
        run: |
          cd example
          flutter test integration_test/integration_test.dart

      # Retry: Integration testing with GitHub Actions is unstable.
      - name: Retry integration tests
        id: Retry-integration-tests
        timeout-minutes: 15
        if: steps.Run-integration-tests.outcome == 'failure'
        run: |
          flutter clean && flutter pub get
          cd example
          flutter clean && flutter pub get
          flutter test integration_test/integration_test.dart

