name: CI

on:
  push:

jobs:
  ios:
    timeout-minutes: 120
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14 Pro Max
      
      - name: Build
        run: |
          cd example
          flutter build ios --simulator --target=integration_test/integration_test.dart

      - name: Analyze
        run: flutter analyze

      - name: Run integration tests
        timeout-minutes: 60
        run: |
          cd example
          flutter test integration_test/integration_test.dart --timeout 3000s

  android:
    timeout-minutes: 120
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31,30,29,28,27,26,25,24]
        target: [default]
      fail-fast: true
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - name: Kill emulator if running
        run: |
          if adb devices | grep -q emulator-5554 ; then
            adb -s emulator-5554 emu kill || echo "Failed to kill emulator-5554"
          else
            echo "emulator-5554 is not running"
          fi
      
      # More info on https://github.com/ReactiveCircus/android-emulator-runner    
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-boot-timeout: 1800
          working-directory: ./example
          script: |
            echo ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=1800 >> $GITHUB_ENV
            flutter test integration_test/integration_test.dart
