name: CI

on:
  push:

jobs:
  setup:
    runs-on: macos-latest
    steps:
     - name: Check out
       uses: actions/checkout@v3
     
     - name: Setup Flutter SDK
       uses: subosito/flutter-action@v2
       with:
         channel: beta

     - name: Cache Flutter SDK
       uses: actions/cache@v3
       with:
         path: /opt/hostedtoolcache/Flutter
         key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}-${{ github.run_id }}

     - name: Cache Flutter packages
       uses: actions/cache@v3
       with:
         path: ~/.pub-cache
         key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}-${{ github.run_id }}

     - name: Install packages
       run: flutter --disable-telemetry && flutter pub get

     - name: Analyze
       run: flutter analyze

  ios:
    needs: setup
    timeout-minutes: 120
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}-${{ github.run_id }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}-${{ github.run_id }}

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14 Pro Max
      
      - name: Build
        timeout-minutes: 30
        run: |
          cd example
          flutter build ios --simulator --target=integration_test/integration_test.dart

      - name: Run integration tests
        timeout-minutes: 30
        run: |
          cd example
          flutter test integration_test/integration_test.dart --timeout none

  android:
    needs: setup
    timeout-minutes: 120
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31,30,29,28,27,26,25,24]
      fail-fast: true
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}-${{ github.run_id }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}-${{ github.run_id }}

      - name: Install Flutter dependencies
        run: flutter pub get ./example

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-boot-timeout: 1800
          force-avd-creation: false
          profile: pixel_6_pro
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."

      # See: https://github.com/ReactiveCircus/android-emulator-runner
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          working-directory: ./example
          arch: x86_64
          emulator-boot-timeout: 1800
          force-avd-creation: false
          profile: pixel_6_pro
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            flutter test integration_test/integration_test.dart --timeout 1800s