name: CI

on:
  push:

jobs:
  ios:
    timeout-minutes: 120
    strategy:
      matrix:
        device:
          - iPhone 14 Pro Max Simulator
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: List all simulators
        run: xcrun xctrace list devices

      - name: Start Simulator
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk 'NR==1{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - name: Build
        run: |
          cd example
          flutter build ios --simulator --target=integration_test/integration_test.dart

      - name: Analyze
        run: flutter analyze

      - name: Run integration tests
        timeout-minutes: 60
        run: |
          cd example
          flutter test integration_test/integration_test.dart

  android:
    timeout-minutes: 120
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31,30,29,28,27,26,25,24]
        target: [default]
      fail-fast: true
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example

      # More info on https://github.com/ReactiveCircus/android-emulator-runner    
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-boot-timeout: 3000
          working-directory: ./example
          script: |
            echo ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=3000 >> $GITHUB_ENV
            flutter test integration_test/integration_test.dart
