name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  windows:
    needs: set-up
    timeout-minutes: 60
    strategy:
      matrix:
        windows-version: [10]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        timeout-minutes: 10
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Run integration tests
        id: Run-integration-tests
        timeout-minutes: 5
        run: |
          flutter doctor -v
          cd example
          flutter test integration_test/integration_test.dart windows -v

 