name: CI

on:
  push:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  ios:
    needs: set-up
    timeout-minutes: 60
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        timeout-minutes: 8
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      
      - uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14 Pro Max
      
      - name: Cache applesimutils
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/Homebrew/Library/Taps/wix/homebrew-brew
            /usr/local/Cellar/applesimutils
          key: ${{ runner.os }}-brew-applesimutils

      - name: Grant permission
        run: |
          brew link applesimutils
          brew tap wix/brew
          brew install applesimutils
          cd example
          applesimutils --booted --bundle studio.midoridesign.galExample --setPermissions photos=YES

      - name: Run integration tests
        id: Run-integration-tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd example
          flutter test integration_test/integration_test.dart

      - name: Retry integration tests
        id: Retry-integration-tests
        continue-on-error: true
        timeout-minutes: 10
        if: steps.Run-integration-tests.outcome == 'failure'
        run: |
          flutter clean && flutter pub get
          cd example
          flutter clean && flutter pub get
          flutter test integration_test/integration_test.dart

      - name: Re:Retry integration tests
        timeout-minutes: 10
        if: steps.Retry-integration-tests.outcome == 'failure'
        run: |
          flutter clean && flutter pub get
          cd example
          flutter clean && flutter pub get
          flutter test integration_test/integration_test.dart

