name: CI

on:
  push:

jobs:
  ios:
    timeout-minutes: 120
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14 Pro Max
      
      - name: Build
        run: |
          cd example
          flutter build ios --simulator --target=integration_test/integration_test.dart

      - name: Analyze
        run: flutter analyze

      - name: Run integration tests
        timeout-minutes: 60
        run: |
          cd example
          flutter test integration_test/integration_test.dart --timeout 3000s

  android:
    timeout-minutes: 120
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31,30,29,28,27,26,25,24]
        target: [default]
      fail-fast: true
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get ./example

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          arch: x86_64
          script: echo "Generated AVD snapshot for caching."

      # More info on https://github.com/ReactiveCircus/android-emulator-runner
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          emulator-boot-timeout: 1800
          working-directory: ./example
          script: |
            adb kill-server
            adb start-server
            flutter test integration_test/integration_test.dart --timeout 1800s