name: CI

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Check out
       uses: actions/checkout@v3

     - name: Cache Flutter SDK
       uses: actions/cache@v2
       with:
         path: /opt/hostedtoolcache/Flutter
         key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}
         restore-keys: |
           ${{ runner.os }}-flutter-
     - name: Setup Flutter SDK
       uses: subosito/flutter-action@v2
       with:
         channel: beta

     - name: Cache Flutter packages
       uses: actions/cache@v2
       with:
         path: ~/.pub-cache
         key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
         restore-keys: |
           ${{ runner.os }}-pub-
     - name: Install packages
       run: flutter --disable-telemetry && flutter pub get

     - name: Analyze
       run: flutter analyze

  ios:
    timeout-minutes: 120
    strategy:
      fail-fast: true
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Cache Flutter packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter dependencies
        run: flutter pub get ./example
      
      - uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14 Pro Max
      
      - name: Build
        run: |
          cd example
          flutter build ios --simulator --target=integration_test/integration_test.dart

      - name: Run integration tests
        timeout-minutes: 60
        run: |
          cd example
          flutter test integration_test/integration_test.dart --timeout 3000s

  android:
    timeout-minutes: 120
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31,30,29,28,27,26,25,24]
        target: [google_apis]
      fail-fast: true
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
          cache: gradle

      - name: Cache Flutter packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter dependencies
        run: flutter pub get ./example

      # More info on https://github.com/ReactiveCircus/android-emulator-runner
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-boot-timeout: 3000
          working-directory: ./example
          script: |
            flutter test integration_test/integration_test.dart --timeout 3000s