name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  macos:
    needs: set-up
    timeout-minutes: 60
    strategy:
      max-parallel: 1
      matrix:
        macos-version: [12]
      fail-fast: false
    runs-on: macos-${{ matrix.macos-version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        timeout-minutes: 10
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Run integration tests
        id: Run-integration-tests
        continue-on-error: true
        timeout-minutes: 15
        run: |
          cd example
          flutter test integration_test/integration_test.dart -d macos

      - name: Retry integration tests
        id: Retry-integration-tests
        timeout-minutes: 15
        if: steps.Run-integration-tests.outcome == 'failure'
        run: |
          flutter clean && flutter pub get
          cd example
          flutter clean && flutter pub get
          flutter test integration_test/integration_test.dart -d macos

 